version: '3'

# see .env file for compose variables

services:
  config-server:
    image: "net.ins.marketplace/config-server:${CONFIG_SERVER_TAG}"
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - SPRING_PROFILES_ACTIVE=keystore
      - KEYSTORE_PWD=storepass123
      - KEY_PWD=keypass123
      - SERVER_PORT=8888
    volumes:
      - "~/.ssh:/root/.ssh"

  eureka:
    image: "net.ins.marketplace/eureka:${EUREKA_TAG}"
    depends_on:
      - config-server
    ports:
      - "8763:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - CONFIG_HOST=$HOSTNAME
