version: '3'

# see .env file for compose variables
# docker-compose up -e KEYSTORE_PWD=... -e KEY_PWD=...
# docker-compose up mongo

services:
  mongo:
    image: "mongo:${MONGODB_TAG}"
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    deploy:
      replicas: 1

  config-server:
    image: "net.ins.hw.netflix/config-server:${CONFIG_SERVER_TAG}"
    depends_on:
      - eureka
#    command: ["sh", "-c", "./wait-for-it.sh", "127.0.0.1:${EUREKA_PORT}", "java", "-jar", "/opt/config-server-${CONFIG_SERVER_TAG}.jar"]
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - SPRING_PROFILES_ACTIVE=keystore,organization
      - KEYSTORE_PWD="${KEYSTORE_PWD}"
      - KEY_PWD="${KEY_PWD}"
      - SERVER_PORT="${CONFIG_SERVER_PORT}"
#    volumes:
#      - "~/.ssh:/root/.ssh"

  eureka:
    image: "net.ins.hw.netflix/eureka:${EUREKA_TAG}"
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - CONFIG_HOST=$HOSTNAME
