#!/bin/bash
script_full_path=$(dirname "$0")
keytool -genkeypair -alias config-server-key \
       -keyalg RSA -keysize 4096 -sigalg SHA512withRSA \
       -dname 'CN=Config Server,OU=net.ins,O=Insomnium' \
       -keypass keypass123 -keystore "$script_full_path/config-server.jks" \
       -storepass storepass123
