server:
 port: ${PORT:9999}

# github OAuth2 client settings ('ownclient' profile for config-server)
github:
  client:
    clientId: ... # loads from config-server ('{cipher}')
    clientSecret: ... # loads from config-server ('{cipher}')
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

# facebook OAuth2 client settings ('ownclient' profile for config-server)
facebook:
  client:
    clientId: ... # loads from config-server ('{cipher}')
    clientSecret: ... # loads from config-server ('{cipher}')
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

# our own Authorization Server client settings ('organization' profile for config-server)
security:
  oauth2:
    client:
      clientId: ... # loads from config-server ('{cipher}')
      clientSecret: ... # loads from config-server ('{cipher}')
      scope: read,write
      auto-approve-scopes: '.*'

allowed:
    origins:
      - 'http://localhost:9999'

logging.level:
  root: info
  org.springframework.security: debug
